import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { Header } from "@/components/Header";
import { Main } from "@/components/Main";
import { Footer } from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  useEffect(() => {
    console.log('useEffect вызван');
    const script = document.createElement('script');
    script.src = "/js/carousel.js";
    script.async = true;
    document.body.appendChild(script);

    return () => {
      console.log('Очистка скрипта');
      document.body.removeChild(script);
    };
  }, []);

  return (
    <>
      <Head>
        <title>React by FG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        // className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Header />
          <Main />
          <Footer />
        </main>
      </div>
    </>
  );
}
